### ISSUE TITLE
GStreamer -- Enhanced Caching Research

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/gmusic#50]
@NullVoxPopuli, want to help me look into improving caching on GStreamer at some point?

Submitting as an issue so we have a place to discuss.

**Comment by NullVoxPopuli** [comment]
Sure - what's the end goal / expected behavior?

**Comment by etkirsch** [comment]
Improved caching of songs. MobileClient invalidates stream urls after a minute, and gstreamer can only cache so much so quickly. Every now and then you wind up with gstreamer being unable to cache the entire song before the stream invalidates, so gmusic is unable to play everything. So do we keep requesting more data from the client every minute, or what? What if the user goes offline and can't contact Google?

Additionally, is there a way to cache more than one song at a time? Something like a [GstPipeline](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstPipeline.html)? I'm not even sure this is the right usage of that element.

Is there a way to access song stream data from GStreamer? We could even potentially tie in Orpheus, if so...

**Comment by NullVoxPopuli** [comment]
Some formatting:

### Goal
Improved caching of the playback of songs

### Problem
Every now and then you wind up with gstreamer being unable to cache the entire song before the stream invalidates, so gmusic is unable to play everything.

### Questions
 - Do we keep requesting more data from the client every minute? (or something similar?)
 - What if the user goes offline and can't contact Google?
 - Can we cache more than one song at a time? (ref:  [GstPipeline](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstPipeline.html) )
 - Is there a way to access the data stream from GStreamer? To hook in other applications

**Comment by etkirsch** [comment]
:+1:

**Comment by NullVoxPopuli** [comment]
I think a lot of this will depend on how much Google will give us.

Right now, I have a 50mbit down connection, so that should be plenty to cache an entire song in a couple seconds. So, we may just have to play with what data we get from google, and how often we need to do that... 
the bandwidth is more than capable - I think if there is a limitation, it may be set by Google -- but we'll see. 

If the user goes offline, there should be error handling or some detection of offline status. (This happened to me this morning, and my gmusic kinda just froze, and didn't do anything)

I'm not sure GstPipeline is what we want, but we'll see.. I just skimmed it, and low level shenanigans isn't my specialty.

**Comment by etkirsch** [comment]
Yeah at the very least the `gmusic.player.PlayList` element should have some sort of error handling in it. Or, maybe `gmusic.player.PlayerController`. As it exists right now, if there's an error it will simply just go to the next song, leading to the whole infinite loop/freezing issue you encountered. I'll come up with a way to address that.
